name: Code formatting

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  format:
    name: Check Prettier formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check formatting
        run: |
          if ! yarn format:check; then
            echo "::error title=Code formatting::Run 'yarn format' to fix formatting issues"
            echo ""
            echo "Unformatted files:"
            yarn prettier --list-different . || true
            exit 1
          fi
          echo "✅ Code formatting is correct!"
